name: SubTaxes
version: 0.1-SNAPSHOT
author: DenisMasterHerobrine, Rikonardo
main: dev.denismasterherobrine.subtaxes.SubTaxes
api-version: 1.16

commands:
  adm:
  farms:
    description: Sub-command for farms
    usage: /farms add [Farm_Name]
  tax: